version: "3"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: runner
    image: run-make-web
    container_name: run-make-web
    tty: true
    volumes:
      - ./web:/app
    working_dir: /app
    environment:
      - READ_DJANGO_ENV_FILE=true
    env_file:
      - ./web/.env
    ports:
      - "8000:8000"
    profiles:
      - local
    depends_on:
      - db
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: run-make-db
    container_name: run-make-db
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data/
    env_file:
      - ./db/.env
    profiles:
      - local
